export const unidades = [
    {label: 'SMS – Coordenação Atenção Básica', value: 'sms-coord-atencao-basica'},
    {label: 'SMS - Assessoria', value: 'sms-assessoria'},
    {label: 'SMS – Coordenação de Suprimentos', value: 'sms-coord-suprimentos'},
    {label: 'SMS - Coordenação de Odontologia', value: 'sms-coord-odontologia'},
    {label: 'NUVE', value: 'nuve'},
    {label: 'Espaço Saúde', value: 'espaco-saude'},
    {label: 'Estomaterapia - Feridas', value: 'estomaterapia-feridas'},
    {label: 'Programa IST/AIDS', value: 'programa-ist-aids'},
    {label: 'Clínica do Bebê', value: 'clinica-do-bebe'},
    {label: 'Equipe Emulti', value: 'equipe-emulti'},
    {label: 'Consultório na Rua', value: 'consultorio-na-rua'},
    {label: 'Ambulatório de Hormônioterapia/ Endócrino', value: 'ambulatório-hormonio-endocrino'},
    {label: 'Farmácia Municipal', value: 'farmacia-municipal'},
    {label: 'UBS CSI', value: 'ubs-csi'},
    {label: 'UBS CECAP', value: 'ubs-cecap'},
    {label: 'UBS JD CRISTINA', value: 'ubs-jd-cristina'},
    {label: 'UBS COHAB I', value: 'ubs-cohab-i'},
    {label: 'UBS SÃO LUCIO', value: 'ubs-sao-lucio'},
    {label: 'UBS VL. JARDIM', value: 'ubs-vl-jardim'},
    {label: 'USF COMERCIÁRIOS', value: 'usf-comerciarios'},
    {label: 'USF REAL PARK', value: 'usf-real-park'},
    {label: 'USF JD PEABIRU', value: 'usf-jd-peabiru'},
    {label: 'USF COHAB IV - Cachoeirinha', value: 'usf-cohab-iv-cachoeirinha'},
    {label: 'USF MARAJOARA', value: 'usf-marajoara'},
    {label: 'USF CÉSAR NETO', value:'usf-cesar-neto'},
    {label: 'USF VITORIANA', value:'usf-vitoriana'},
    {label: 'USF JD IOLANDA', value:'usf-jd-iolanda'},
    {label: 'USF JD SANTA ELISA', value:'usf-jd-santa-elisa'},
    {label: 'USF JD AEROPORTO', value:'usf-jd-aeroporto'},
    {label: 'USF SANTA MARIA', value:'usf-santa-maria'},
    {label: 'USF RUBIÃO JR ZONA URBANA/ZONA RURAL', value:'usf-rubiao-jr-zona-urbana-zona-rural'},
    {label: 'USF Caimã', value:'usf-caima'},
    {label: 'USF Lavapés', value:'usf-lavapes'},
    {label: 'CEREST', value:'cerest'},
    {label: 'CSE – UVL', value:'cse-uvl'},
    {label: 'SAMU', value:'samu'},
    {label: 'CEO', value:'ceo'},
    {label: 'Residência Terapêutica I', value:'residencia-terapeutica-i'},
    {label: 'Residência Terapêutica II', value:'residencia-terapeutica-ii'},
    {label: 'Residência Terapêutica III', value:'residencia-terapeutica-iii'},
    {label: 'CAPS infantil', value:'caps-infantil'},
    {label: 'Almoxarifado', value:'almoxarifado'},
    {label: 'Dose em casa', value:'dose-em-casa'},
    {label: 'Unidade de Avaliação e Controle - UAC', value:'unidade-avaliacao-controle-uac'},
    {label: 'CAPS I', value:'caps-i'},
    {label: 'Central de Esterilização', value:'central-esterilizacao'},
    {label: 'Raio-X Municipal', value:'raio-x-municipal'},
    {label: 'Oftalmologia Complementar', value:'oftalmologia-complementar'},
]